/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/[id]/': RouteRecordInfo<
      '/project/[id]/',
      '/project/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/project/[id]/[artifact]': RouteRecordInfo<
      '/project/[id]/[artifact]',
      '/project/:id/:artifact',
      { id: ParamValue<true>, artifact: ParamValue<true> },
      { id: ParamValue<false>, artifact: ParamValue<false> },
      | never
    >,
    '/project/[id]/epics/': RouteRecordInfo<
      '/project/[id]/epics/',
      '/project/:id/epics',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/project/[id]/epics/[epicId]': RouteRecordInfo<
      '/project/[id]/epics/[epicId]',
      '/project/:id/epics/:epicId',
      { id: ParamValue<true>, epicId: ParamValue<true> },
      { id: ParamValue<false>, epicId: ParamValue<false> },
      | never
    >,
    '/project/create': RouteRecordInfo<
      '/project/create',
      '/project/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/roadmap': RouteRecordInfo<
      '/roadmap',
      '/roadmap',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/project/[id]/index.vue': {
      routes:
        | '/project/[id]/'
      views:
        | never
    }
    'src/pages/project/[id]/[artifact].vue': {
      routes:
        | '/project/[id]/[artifact]'
      views:
        | never
    }
    'src/pages/project/[id]/epics/index.vue': {
      routes:
        | '/project/[id]/epics/'
      views:
        | never
    }
    'src/pages/project/[id]/epics/[epicId].vue': {
      routes:
        | '/project/[id]/epics/[epicId]'
      views:
        | never
    }
    'src/pages/project/create.vue': {
      routes:
        | '/project/create'
      views:
        | never
    }
    'src/pages/roadmap.vue': {
      routes:
        | '/roadmap'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
